
title: alox.sh
description: Documentation of alox.sh Go package
theme: just-the-docs
logo: /assets/logo-transparent-bw-usd.png
# logo: /assets/logo-transparent-bw.png

url: https://alox.sh
port: 4002

exclude:
  - tmp

collections:
  examples:
    output: true

just_the_docs:
  collections:
    examples:
      name: Examples

callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: red

footer_content: "Distributed under an <a href=\"https://github.com/alox-sh/alox/tree/master/LICENSE.txt\">MIT license</a>"

# aux_links:
#   GitHub: https://github.com/alox-sh/alox
